[package]
name = "maze_maker"
version = "0.1.0"
authors = ["amirhosein"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.6.0-rc1"
glam = "0.15.2"